import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; 
import Header from "./components/Header";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Topbar from "./components/Topbar";
import Hero from "./components/Hero";
import AllProduct from "./components/allProducts";
import AboutPopularProduct from "./components/aPopularProducts";
import AboutSection from "./components/aSection";
import Categories from "./components/Categorioes";
import CompanyLogo from "./components/companyLogo";
import AboutHero from "./components/aHero";
import HotProduct from "./components/hotProduct";
import Instagram from "./components/Instagram";
import { Button } from "@/components/ui/button";
import { Badge, Contact } from "lucide-react";
import Cart from "./contactus/page";
import { FaQ } from "react-icons/fa6";




const inter = Inter({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "templet-08",
  description: "Generated by Muhammad Shoaib",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Topbar />
        <Header />
        <Navbar />
        <Hero />
        <AllProduct />
        <AboutPopularProduct />
        <AboutSection />
        <Categories />
        <CompanyLogo />
        <AboutHero />
        <HotProduct />
        <Instagram />
        <Button />
        <Badge />
        <Cart />
        <FaQ />
        <Contact />
        <Badge />
        <Button />
        
        
        

        
        
        
        
      
        <main>{children}</main>
        <Footer />
        
        
      </body>
    </html>
  );
}
